openapi: 3.0.2
servers:
  - url: /v3
info:
  description: |-

  version: 1.0.17
  title: Swagger Storyboard - OpenAPI 3.0
  contact:
    email: al4363@columbia.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: stories
    description: Everything about your stories
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: user
    description: Operations about user
paths:
  /stories:
    post:
      tags:
        - stories
      summary: Add a new story to the market
      description: Add a new story to the market
      operationId: uploadStory
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '405':
          description: Invalid input
      security:
        - Cognito: []
      requestBody:
        description: Upload new story in the market
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Story'
          application/xml:
            schema:
              $ref: '#/components/schemas/Story'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Story'
    
  '/stories/{userID}':
    get:
      tags:
        - stories
      summary: Find Story Recommendations for user
      description: Get recommendations based on user purchase and likes
      operationId: findStoryByUser
      parameters:
        - name: userID
          in: path
          description: userID for recommendations
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Story'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Story'
        '400':
          description: Invalid status value
      security:
        - Cognito: []
  '/stories/{genre}':
    get:
      tags:
        - stories
      summary: Finds stories by genre
      description: Finds stories by genre
      operationId: findStoriesByGenre
      parameters:
        - name: genre
          in: path
          description: genre for recommendations
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Story'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Story'
        '400':
          description: Invalid tag value
      security:
        - Cognito: []
  '/stories/{storyId}':
    get:
      tags:
        - stories
      summary: Find stories by ID
      description: Returns a single story
      operationId: getStoryById
      parameters:
        - name: storyId
          in: path
          description: ID of story to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Story'
            application/json:
              schema:
                $ref: '#/components/schemas/Story'
        '400':
          description: Invalid StoryID supplied
        '404':
          description: Story not found
      security:
        - Cognito: []
    delete:
      tags:
        - stories
      summary: Deletes a story
      description: ''
      operationId: deleteStory
      parameters:
        - name: storyId
          in: path
          description: Story id to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid storyID value
      security:
        - Cognito: []
            
  '/likestories':
    post:
      tags:
        - stories
      summary: Like stories by ID
      description: Like stories by ID
      operationId: likeStoryById
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid StoryID supplied
        '404':
          description: Story not found
      requestBody:
        description: Like stories by ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAction'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserAction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAction'
      security:
        - Cognito: []
  '/buystories':
    post:
      tags:
        - stories
      summary: Buy stories by ID
      description: Buy stories by ID
      operationId: buyStoryById
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid StoryID supplied
        '404':
          description: Story not found
      requestBody:
        description: Like stories by ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAction'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserAction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAction'
      security:
        - Cognito: []
  '/genImage':
    post:
      tags:
        - stories
      summary: Generate cover image for story
      description: ''
      operationId: uploadPrompt
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Story'
            application/json:
              schema:
                $ref: '#/components/schemas/Story'
        '400':
          description: Invalid StoryID supplied
        '404':
          description: Story not found
      requestBody:
        description: Generate Image for story
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Story'
          application/xml:
            schema:
              $ref: '#/components/schemas/Story'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Story'
      security:
        - Cognito: []
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation


components:
  schemas:
    UserAction:
      x-swagger-router-model: io.swagger.storyboard.model.Purchase
      properties:
        userid:
          type: string
          example: CDAB10
        storyid:
          type: string
          example: AB10
      xml:
        name: order
      type: object

    User:
      x-swagger-router-model: io.swagger.storyboard.model.User
      properties:
        id:
          type: string
          example: CDAB10
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: 12345
      xml:
        name: user
      type: object
    Story:
      x-swagger-router-model: io.swagger.storyboard.model.Story
      properties:
        id:
          type: string
          example: AB10
        name:
          type: string
          example: Wallflower
        genre:
          type: string
          example: horror
        storybody:
          type: string
          example: A king of the hill
        imageprompt:
          type: string
          example: A man in rain
        imageurl:
          type: string
          example: http://s3.story.jpg
        language:
          type: string
          example: english
        audiourl:
          type: string
          example: http://s3.story.mp3
        message:
          type: string
          example: some message
        
      xml:
        name: story
      type: object
    ApiResponse:
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
      type: object
  requestBodies:
    Story:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Story'
        application/xml:
          schema:
            $ref: '#/components/schemas/Story'
      description: Story object that needs to be added to the store
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
        application/xml:
          schema:
            $ref: '#/components/schemas/User'
      description: User object
    UserAction:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserAction'
        application/xml:
          schema:
            $ref: '#/components/schemas/UserAction'
      description: User object
  securitySchemes:
    Cognito:
      type: "apiKey"
      name: "Cognito_token"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"